feat: export html parts renderers
gravity-ui/app-layout pull request #38
Opened 2024-03-04 09:30 UTC by Volodomor

Pull Request for RFC https://github.com/gravity-ui/rfc/issues/7

2024-03-04 13:48 UTC, obenjiro commented
@korvin89 @ValeraS @sofiushko

I would appreciate it if you could take some time to review this pull request. Thank you.

2024-03-06 10:03 UTC, ValeraS requested changes

2024-03-12 16:46 UTC, Volodomor commented on src/utils/generateRenderContent.ts
> +        className: bodyClasses,
Returned to the original version

2024-03-17 10:28 UTC, ValeraS requested changes

2024-03-17 10:28 UTC, ValeraS commented on src/types.ts
> +    className: string[];
```suggestion
    /** @deprecated use attributes.class instead */
    className: string[];
    attributes: Attributes;
```

2024-03-17 10:28 UTC, ValeraS commented on src/types.ts
>          renderContent: RenderContent;
```suggestion
        renderContent: Omit<RenderContent, 'bodyContent'> & {bodyContent: OldBodyContent};
```

where 
```ts
type OldBodyContent = Omit<BodyContent, 'attributes'>;
```

2024-03-17 10:28 UTC, ValeraS commented on README.md
> +  };
```suggestion
```

2024-03-17 10:28 UTC, ValeraS commented on README.md
> +        <body ${helpers.attrs(bodyAttributes)}>
```suggestion
        <body ${helpers.attrs(bodyContent.attributes)}>
```

2024-03-17 10:32 UTC, ValeraS commented on src/utils/generateRenderContent.ts
> +        className: bodyClasses,
Let's add attributes to body content after plugins.

2024-03-18 08:19 UTC, Volodomor commented
@ValeraS done

2024-03-18 09:19 UTC, ValeraS approved these changes

2024-03-19 14:57 UTC, merged

2024-03-20 08:15 UTC, Volodomor commented
@ValeraS выпусти, пожалуйста, новую версию